version: 1

formatters:
  custom_fmt:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: custom_fmt
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: custom_fmt
    filename: nicobert.log
loggers:
  nicobert:
    level: INFO
    handlers: [console, file]
    propagate: no
    qualname: nicobert
root:
  level: INFO
